spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydatabase
    username: user
    password: userpassword
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    property-naming-strategy: SNAKE_CASE

aws:
  s3:
    access-key: ${S3-KEY}
    secret-key: ${S3-SECRET}
    bucket: ${S3-BUCKET}

