= 회원 API
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 2
:sectlinks:

[[회원API]]
== 회원 관련 API

[[회원상세조회]]
=== 회원 상세조회 성공

operation::member-controller-test/멤버상세조회[snippets='http-request,query-parameters,response-body,response-fields']

+

[[회원상세조회_실패_존재하지않는멤버]]
=== 회원 상세조회 실패 (존재하지 않는 멤버)

operation::member-controller-test/멤버상세조회실패_존재하지않는멤버[snippets='http-request,response-body']



[[회원프로필목록조회]]
=== 회원 프로필 목록 조회 성공

operation::member-controller-test/멤버_프로필_리스트조회[snippets='http-request,query-parameters,response-body,response-fields']


[[회원프로필목록조회실패]]
=== 회원 프로필 목록 조회 실패 (없는 멤버 조회)

operation::member-controller-test/멤버_프로필_리스트조회_실패_존재하지않는멤버[snippets='http-request,response-body']


[[그루적립]]
=== 그루 적립 성공

operation::member-controller-test/그루_적립[snippets='http-request,request-fields,response-body,response-fields']


[[그루적립실패]]
=== 그루 적립 실패 멤버없음

operation::member-controller-test/그루_적립_실패_멤버없음[snippets='http-request,response-body']

[[고소장사용]]
=== 고소장 사용

operation::member-controller-test/고소장_사용[snippets='http-request,request-fields,http-response']

[[고소장사용실패]]
=== 고소장 사용 실패 멤버 없음

operation::member-controller-test/고소장_사용_고소장없음[snippets='http-request,http-response']

[[고소장카운트증가]]
=== 고소장 카운트 증가

operation::member-controller-test/고소장_카운트_증가[snippets='http-request,request-fields,http-response']

[[닉네임중복검사중복]]
=== 닉네임 중복검사 (응답 중복일때)

operation::member-controller-test/중복_닉네임_검사_중복임[snippets='http-request,path-parameters,http-response']

[[닉네임중복검사중복아님]]
=== 닉네임 중복임 (응답 중복아닐떄)

operation::member-controller-test/중복_닉네임_검사_중복아님[snippets='http-request,path-parameters,http-response']

[[닉네임변경]]
=== 닉네임 변경 성공

operation::member-controller-test/닉네임변경[snippets='http-request,request-fields,http-response']

[[닉네임변경실패]]
=== 닉네임 변경 실패 (중복된 닉네임)

operation::member-controller-test/닉네임변경_실패_중복된닉네임[snippets='http-request,request-fields,http-response']

[[프로필사진변경]]
=== 프로필 사진 변경 성공

operation::member-controller-test/프로필사진_변경[snippets='httpie-request,request-parts,http-response']

[[프로필사진변경실패]]
=== 프로필 사진 변경 실패

operation::member-controller-test/프로필사진_변경실패_s3업로드실패[snippets='httpie-request,http-response']

[[테스트완료]]
=== 테스트 완료 성공

operation::member-controller-test/테스트완료[snippets='httpie-request,request-fields,http-response,response-fields']

[[테스트완료실패]]
=== 테스트 완료 실패 (이미 테스트 완료한 사용자)

operation::member-controller-test/테스트완료실패_이미테스트완료[snippets='httpie-request,request-fields,http-response']
