version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: groodatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
