spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssafy?characterEncoding=UTF-8
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: member-service
  web:
    resources:
      static-locations=classpath:/static/docs/:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false

cookie:
  domain: ${COOKIE_DOMAIN}

jwt:
  secret-key: ${JWT_SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${S3_KEY}
      secret-key: ${S3_SECRET}
    s3:
      bucket: ${S3_BUCKET}

auth:
  kakao:
    token-request-uri: ${KAKAO_TOKEN_REQUEST_URI}
    member-info-request-uri: ${KAKAO_MEMBER_REQUEST_URI}
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    login-uri: ${KAKAO_LOGIN_URI}
    unlink-uri: ${KAKAO_UNLINK_URI}
    client-secret: ${KAKAO_CLIENT_SECRET}
    client-uri: ${KAKAO_CLIENT_URI}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka
