= 탄소중립포인트 API
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 2
:sectlinks:

[[연계기업API]]
== 연계기업API

[[연계기업목록조회]]
=== 연계기업 목록조회 성공

operation::company-controller-test/회사목록조회[snippets='http-request,query-parameters,http-response,response-fields']
+

[[연계기업목록조회_잘못된_ActivityType]]
=== 연계기업 목록조회 실패 (잘못된 ActivityType)

operation::company-controller-test/회사목록조회_잘못된_활동종류[snippets='http-request,http-response']
+

[[연계기업목록조회_JWT없는요청]]
=== 연계기업 목록조회 실패 (JWT 없는 요청)

operation::company-controller-test/회사목록조회_jwt없는_요청[snippets='http-request,http-response']
+

[[연계기업목록조회_잘못된JWT]]
=== 연계기업 목록조회 실패 (잘못된 JWT)

operation::company-controller-test/회사목록조회_jwt잘못된_요청_테스트[snippets='http-request,http-response']
+

[[연계기업상세조회]]
=== 연계기업 상세조회 성공

operation::company-controller-test/회사상세조회[snippets='http-request,path-parameters,http-response,response-fields']
+

[[연계기업상세조회_PK잘못됨]]
=== 연계기업 상세조회 PK잘못됨

operation::company-controller-test/회사상세조회_pk잘못됨[snippets='http-request,http-response,response-fields']
+

[[연계기업상세조회_없는회사]]
=== 연계기업 상세조회 없는회사

operation::company-controller-test/회사상세조회_없는_회사pk[snippets='http-request,http-response,response-fields']
+

[[연계기업연동]]
=== 연계기업 연동 성공

operation::company-controller-test/회사연동[snippets='http-request,path-parameters,http-response,response-fields']
+

[[연계기업연동실패_이미연동됨]]
=== 연계기업 연동 실패 이미 연동됨

operation::company-controller-test/회사연동_이미연동됨[snippets='http-request,http-response,response-fields']
+

[[연계기업연동_없는회사]]
=== 연계기업 연동 실패 없는 회사

operation::company-controller-test/회사연동_없는회사[snippets='http-request,http-response,response-fields']
+

[[연계기업연동_PK잘못됨]]
=== 연계기업 연동 실패 잘못된 PathVariable

operation::company-controller-test/회사연동_pk잘못됨[snippets='http-request,http-response,response-fields']
+

[[연계기업연동해제]]
=== 연계기업 연동해제 성공

operation::company-controller-test/회사연동해제[snippets='http-request,path-parameters,http-response,response-fields']
+

[[연계기업연동해제_연동되지않은회사]]
=== 연계기업 연동해제 실패 연동되지않은 회사

operation::company-controller-test/회사연동해제_연동되지않은회사[snippets='http-request,http-response,response-fields']
+

[[탄소중립활동포인트API]]
== 탄소중립활동포인트 API

[[탄소중립활동포인트조회]]
=== 탄소중립활동포인트 조회

operation::cpoint-controller-test/탄소중립포인트조회[snippets='http-request,http-response,response-fields']
+

[[탄소중립활동포인트조회_실패_JWT없음]]
=== 탄소중립활동포인트 조회 실패 JWT없음

operation::cpoint-controller-test/탄소중립포인트조회_jwt없음[snippets='http-request,http-response']
+

[[탄소중립활동포인트조회_실패_잘못된JWT]]
=== 탄소중립활동포인트 조회 실패 잘못된JWT

operation::cpoint-controller-test/탄소중립포인트조회_잘못된jwt[snippets='http-request,http-response']
+

[[탄소중립활동포인트적립]]
=== 탄소중립활동포인트 적립

operation::cpoint-controller-test/탄소중립포인트적립[snippets='http-request,,request-fields,http-response,response-fields']
+

[[탄소중립활동포인트적립_실패_잘못된_payload]]
=== 탄소중립활동포인트 적립 실패 Payload 잘못됨

operation::cpoint-controller-test/탄소중립포인트적립_잘못된-payload[snippets='http-request,http-response,response-fields']
+

[[탄소중립활동포인트적립_실패_잘못된회사PK]]
=== 탄소중립활동포인트 적립 실패 회사 없음

operation::cpoint-controller-test/탄소중립포인트적립_잘못된회사pk[snippets='http-request,http-response,response-fields']
+

[[탄소중립활동포인트요약조회]]
=== 탄소중립활동포인트 활동요약 조회

operation::cpoint-controller-test/탄소중립활동요약조회[snippets='http-request,http-response,response-fields']
+

[[매장API]]
== 매장 API

[[주변매장조회]]
=== 주변 매장 조회

operation::store-controller-test/매장조회[snippets='http-request,query-parameters,http-response,response-fields']
+

[[주변매장조회_실패_쿼리스트링_없음]]
=== 주변 매장 조회 실패 쿼리스트링 빼먹음

operation::store-controller-test/매장조회_쿼리스트링없음[snippets='http-request,http-response,response-fields']
+

[[주변매장조회_실패_잘못된_쿼리스트링]]
=== 주변 매장 조회 실패 쿼리스트링 빼먹음

operation::store-controller-test/매장조회_잘못된쿼리스트링[snippets='http-request,http-response,response-fields']
+