server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      routes:
        - id: proof-service
          uri: lb://PROOF-SERVICE
          predicates:
            - Path=/proof/**
          filters:
            - CustomAuthFilter
