spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssafy?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: ssafy


  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace