spring:
  datasource:
    url: jdbc:h2:~/test
    username: user
    password: userpassword
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false
