spring:
  datasource:
    url: jdbc:h2:~/test;Mode=MySQL;
    username: user
    password: userpassword
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false
