spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/groodatabase
    username: user
    password: userpassword
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

